groups:
#    - groupa
recipes:
    mac_os_x:
#        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
#        computername: jons-mbp13
    homebrewalt:
        apps:
#           - git-extras
        cask_apps:
#           - sourcetree
